### ISSUE TITLE
github triple backtick code support

### ISSUE THREAD

**Issue by trvsdnn** [textmate/markdown.tmbundle#13]
Github Markdown can use triple backticks to start and end a code section, this is useful because it's the only way to specify a language for syntax highlighting.

Would it be appropriate to include this in the markdown bundle (given it's github flavored markdown)?

As of now README files look a a little sad if you're using the triple backtick syntax.

**Comment by MikeMcQuaid** [comment]
TextMate 2 now has a Markdown (GitHub) bundle under "Bundles" that I think may address many of the folks' desires here (repository for the curious: https://github.com/MikeMcQuaid/GitHub-Markdown.tmbundle).
