### ISSUE TITLE
No hyphen list support. Need to advance on "Return" instead of "Enter"

### ISSUE THREAD

**Issue by chasereeves** [textmate/markdown.tmbundle#14]
I expected the markdown bundle to work the same as previous MD bundle in TM1. 

1. Type a hyphen and space to start a list: "- "
2. type some shit. 
3. hit Return... expected behavior is another "- " being added to the beginning of the next line. This does not happen. 
4. another shot of tequila.... try again. no dice. get terrified/angry. 

I've discovered that this MD bundle expects lists to use asterisks ( * ) instead of hyphens and "Enter" instead of "Return" (fn+return on laptop). Both of these require extra keystrokes (sub-optimal) and it seems unnecessary to change the behavior from TM1.

This is my humble request for an update to this behavior. 

Big fan. Thanks.

**Comment by infininight** [comment]
Corrected in 0630d4c36f6ee555d9e37b6cf1ee47f2b664cfa2.
