### ISSUE TITLE
Extended Markdown Bundle

### ISSUE THREAD

**Issue by Wardrop** [textmate/markdown.tmbundle#15]
Would it be possible add support for a few extended markdown features? I'm mainly thinking of support for the commonly used fenced code blocks. If you're concerned about automatically formatting non-standard markdown, then perhaps this could be something that's turned off by default, which can be enabled within the bundle settings.

I understand someone made a request for full github flavoured markdown support #9. If indeed you'd prefer to split this out into a new bundle using markdown as it's base, can I make a vote for that? I think many of these extensions, at least fenced code blocks, are common enough to warrant making it an official bundle.

Perhaps there's an opportunity here to even support the class hinting that fenced code blocks allow, and which is commonly used for code highlighting. So if someone marks a fenced code block with the ruby class hint, then Markdown can render the content of that code block using the grammer from the ruby bundle. That'd be pretty awesome.

Thoughts?

**Comment by bobrocke** [comment]
```
{  patterns = (
      {  name = 'markup.raw.block.markdown';
         begin = '{% highlight (\w+) %}\n?';
         end = '{% endhighlight %}\n?';
         contentName = 'meta.embedded_$1.markdown';
      },
   );
}
```
Doesn't seem to be working in TextMate 2.0b6.8 after I followed the other directions. I've successfully injected additions to Markdown in other ways, but this isn't working.

What could I have missed?

**Comment by sorbits** [comment]
Probably easiest to troubleshoot if you provide the full grammar so we 
can see e.g. injection scope selector, also describe how you tested it, 
i.e. provide a sample document and expected/actual result using e.g. 
Show Scope.

Also, I suggest using the mailing list for this kind of troubleshooting.

**Comment by MikeMcQuaid** [comment]
TextMate 2 now has a Markdown (GitHub) bundle that I think may address many of the folks' desires here.

**Comment by infininight** [comment]
Since there is a template on how to accomplish extending the Markdown grammar now with the Github grammar I'm going to close this issue.
