### ISSUE TITLE
Feature Request: YAML Font Matter

### ISSUE THREAD

**Issue by bobrocke** [textmate/markdown.tmbundle#27]
Would it be possible for you to add YAML formatting for front matter that is often used in Markdown files?

**Comment by infininight** [comment]
In the grammar in this bundle we want to stick to strict markdown rather than any of the multitude of variants that are out there. New grammars can be created to handle the header items.

**Comment by sorbits** [comment]
It could likely be done via injection and anchored to \A 
(begin-of-document).

See 
https://github.com/textmate/markdown.tmbundle/issues/15#issuecomment-18321960 
for a a how-to on injections.

**Comment by bobrocke** [comment]
The `\A` was the trick I was missing. Thanks!

For anyone following along behind, here's the injected grammar that worked for me:
```
{	patterns = (
		{	name = 'text.html.markdown.yaml';
			begin = '\A^[-]{3}';
			end = '[-]{3}\n';
			patterns = ( { include = 'source.yaml'; } );
		},
	);
}
```
