### ISSUE TITLE
Lists Are Only Found If After A Newline

### ISSUE THREAD

**Issue by bobrocke** [textmate/markdown.tmbundle#29]
The Markdown grammar has this for lists:

```
lists = {
	patterns = (
		{	name = 'markup.list.unnumbered.markdown';
			comment = 'Currently does not support un-indented second lines.';
			begin = '(^|\G)([ ]{0,3})([*+-])([ ]{1,3}|\t)';
			while = '\G([ ]{4}|\t|$)';
			beginCaptures = { 3 = { name = 'punctuation.definition.list.markdown'; }; };
			patterns = (
				{	include = '#list_paragraph'; },
				{	include = '#block'; },
			);
		},
		{	name = 'markup.list.numbered.markdown';
			begin = '(^|\G)([ ]{0,3})([0-9]+\.)([ ]{1,3}|\t)';
			while = '\G([ ]{4}|\t|$)';
			beginCaptures = { 3 = { name = 'punctuation.definition.list.markdown'; }; };
			patterns = (
				{	include = '#list_paragraph'; },
				{	include = '#block'; },
			);
		},
	);
};
```
For some reason it hits for lists starting after a newline:

![hit](https://cloud.githubusercontent.com/assets/2962426/6118041/8481667a-b087-11e4-81b9-733e42540bc5.jpg)

But not right after a paragraph:

![miss](https://cloud.githubusercontent.com/assets/2962426/6118054/9912f388-b087-11e4-8a93-7e984aff0b34.jpg)

And I can't imaging why. The `(^|\G)` capture group should hit looking only at the start of a line, not what precedes it.

Why does it behave wrongly (IMHO)?

**Comment by sorbits** [comment]
Majority of markdown parsers do not consider the latter a list (incl. 
John Gruber’s Markdown.pl), it’s part of the paragraph: 
http://johnmacfarlane.net/babelmark2/?normalize=1&text=This+is+a+list%3A%0A%0A-+foo%0A%0AThis+is+not+a+list%3A%0A-+bar%0A

**Comment by bobrocke** [comment]
Yes, this is a tough one (as are many Markdown interpretations - hence CommonMark). I'm using Parsedown, so was getting the desired behavior with my markup.

Do you know of anyone working on a CommonMark or Parsedown bundle?

If I want to modify the regex to work for Parsedown, I'm still confused about how the existing regex can tell that there is a newline, or not, on the line before. I didn't think TextMate parsed the line before and the `(^|\G)` would have hit with, or without, the preceding newline. Not true?

**Comment by sorbits** [comment]
There is a rule in the Markdown bundle to match paragraphs. While in a 
paragraph context, the other block-level rules (like lists) are not 
active, so that is why you won’t be able to start a list in a 
paragraph, even though the list rule itself does not look at its context 
(the ordering of the rules just makes sure, that the rule is only 
active, when in the proper context).
