### ISSUE TITLE
List auto complete + tab separate font

### ISSUE THREAD

**Issue by chasereeves** [textmate/markdown.tmbundle#30]
TM2 always autocompleted markdown lists. E.g., after typing "- list item one" and hitting return, the next line would display "- ", the hyphen and space there waiting for me with the cursor placed after the space to start writing the next bullet point. 

This no longer happens and I'm wondering why. Is it just my version or do others have this problem? 

Also, when I tab in the text appears in a different font and breaks the page wrap. Screenshot: http://cl.ly/ZrX5

Am I setup wrong on this or is this something in the bundle itself? 

Thanks, all.

**Comment by sanssecours** [comment]
Hi Chase,

the different font is a result of the scope and the setting “Markup: Raw” inside the “Themes Bundle”. Text that is intended 4 spaces/1 tab or more is considered to be [code](http://daringfireball.net/projects/markdown/syntax#precode) — scope `markup.raw.block.markdown`. The setting “Markup: Raw” sets the font for this scope to “Courier”.  Just recently there was a discussion about this behaviour on the [mailing list](http://textmate.1073791.n5.nabble.com/Who-What-Is-Changing-My-Font-td28927.html).

As for the “autocompletion” of lists: This works fine for me. Could you please provide steps to reproduce your problem?

Kind regards,
  René

**Comment by chasereeves** [comment]
Thanks Rene! The "Markup: Raw" theme fixed the font issue. 

For the no list autocomplete, here's a quick screen capture: http://cl.ly/Zwap

**Comment by sanssecours** [comment]
Hi Chase,

unfortunately my Keyboard has no “Enter” key <kbd>⌤</kbd>. Pressing “Function” and “Return” <kbd>fn↩</kbd> — which should be the same as <kbd>⌤</kbd> according to “Keyboard Viewer” — produces new list items when I enter the text from your screen capture. Maybe [reverting to defaults](https://github.com/textmate/textmate/wiki/Reverting-To-Defaults) fixes your problems.

Kind regards,
  René

**Comment by chasereeves** [comment]
Ah, got it. Fn + Return works. That's so helpful... now I wonder if I can change it to work on Return instead of Fn+Return (it worked that way before, wonder why the change). 

So grateful, Sanssecours. Thanks!

**Comment by sanssecours** [comment]
Hi Chase,

> now I wonder if I can change it to work on Return instead of Fn+Return

you can change the shortcut in the “Bundle Editor”:

1. Open the ”Bundle Editor”: <kbd>^⌥⌘B</kbd>
2. Go to “Markdown→Menu Actions→Lists→New Item”
3. Click into the input box right besides “Key Equivalent:”
4. Press Return <kbd>↩</kbd>
5. Save the changes: <kbd>⌘S</kbd>

After that you can create a new list item by pressing “Return”. To write something different use “Enter” <kbd>fn↩</kbd>.

Kind regards,
  René

**Comment by chasereeves** [comment]
You're like a ninja! Thanks, René!
