### ISSUE TITLE
New Item/Subitem broken

### ISSUE THREAD

**Issue by samfearn** [textmate/markdown.tmbundle#33]
Hi,

When I run the new item or new subitem commands I get a ruby error. The parse function that the new item/subitem calls from the markdown.rb file uses a method str.to_a() which doesn't seem to work. This is on OS X Mavericks, which may be using a new version of ruby than this script was expecting?

**Comment by infininight** [comment]
These commands work fine here with the current (2.0) version of TextMate and other support bundles. Are you using 1.x and have you customized anything about the ruby or path variables in TextMate?

**Comment by samfearn** [comment]
Huh, ok must be a local problem then. I'm using text mate 2.0 beta 7.1. The text mate path is $PATH:/opt/local/bin:/usr/local/bin:/usr/texbin and I don't believe I would have changed anything to do with the ruby path, but I'm not sure where I can check. I don't do any ruby programming so theres no reason I should have.

If I create a new markdown document with a list containing a single item 'test' and then hit the new item command I get the error:

/Users/sam/Library/Application Support/Avian/Pristine Copy/Bundles/markdown.tmbundle/Support/lib/markdown.rb:313:in `parse': undefined method `to_a' for "* Test":String (NoMethodError)
	from New Item:11:in `<main>'

**Comment by infininight** [comment]
The error is behaving in an odd way, I would suggest reverting to defaults:

https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

**Comment by samfearn** [comment]
Thanks for the help. Reverting to defaults fixed the items I mentioned.

It seems to have been caused by installing the multimarkdown bundle which is no longer kept very up to date. I have since been able to reinstall that bundle and make sure all the shebangs in the associated commands point to the correct version of ruby and everything now seems to work.

Thanks again for the help.

Sam
