### ISSUE TITLE
Printing Markdown preview crashes TM

### ISSUE THREAD

**Issue by feekApp** [textmate/markdown.tmbundle#43]
Hi,

When printing the Markdown preview (⌃⌥⌘P) via ⌘P to a PDF-file or to Preview.app, crashes TM completely.

fyi, printing via the Multi Markdown bundle goes OK.

--feek

**Comment by feekApp** [comment]
Seems to be fixed in TM 2.0-beta.12 nightly-build.

-- feek

**Comment by infininight** [comment]
Pushed a workaround for this earlier, thanks for the report.
