### ISSUE TITLE
Header with only CJK characters break html

### ISSUE THREAD

**Issue by milligramme** [textmate/markdown.tmbundle#44]
runing 2.0-beta.12.26

Header item will convert to H1-6 with id.
If the contents is only CJK chars, last quotation mark for id is short.

here is a sample.

```md
# 第一階層

top level

## 第二階層

second level

## 第三階層

third level
```

`Show Preview` shots

![screen shot 2016-10-26 10 19 05](https://cloud.githubusercontent.com/assets/294127/19710007/f2d95dec-9b65-11e6-942e-7714f3e603d9.png)

output from `Convert Document to HTML`

```html
<h1 id=">第一階層</h1>

<p>top level</p>

<h2 id=">第二階層</h2>

<p>second level</p>

<h2 id=">第三階層</h2>

<p>third level</p>
```

I expect this output.

```html
<h1 id="">第一階層</h1>

<p>top level</p>

<h2 id="">第二階層</h2>

<p>second level</p>

<h2 id="">第三階層</h2>

<p>third level</p>
```

**Comment by milligramme** [comment]
[Header with only CJK characters break html \#44](https://gist.github.com/milligramme/07e8532dadc8f9cf3e44caa8fa3a2237)

added View Source output

**Comment by sorbits** [comment]
I am not seeing this with neither `multimarkdown` or the default `Markdown.pl`.

Do you have a custom value set for `TM_MARKDOWN`?

**Comment by milligramme** [comment]
I'm sorry.
I also checked Markdown(Github)

after running only default Markdown it fixed.

```rb
p ENV['TM_MARKDOWN']
#=> "eval '/Users/xxxxx/Library/Application Support/TextMate/Managed/Bundles/Markdown (GitHub).tmbundle/Support/bin/redcarpet.rb'"
```

**Comment by sorbits** [comment]
You may want to report the issue to the maintainers of redcarpet.rb.
