### ISSUE TITLE
Hash comments in code blocks

### ISSUE THREAD

**Issue by Zac-Garby** [textmate/markdown.tmbundle#48]
If I make a markdown file containing something like this:

```python
# does something
print("Hello, world")
```

The comment `# does something` is a really big font, since it's displaying as if it were a `<h1>`. If nobody else wants to, I might have a go at fixing this.

**Comment by sorbits** [comment]
A leading `#` character indicates a heading in Markdown, so the font _should_ be big.

If you want support for fenced code blocks then install the GitHub Flavored Markdown bundle via Preferences → Bundles.

**Comment by Zac-Garby** [comment]
I know it indicates a heading, but surely it shouldn't inside a code block?

**Comment by sorbits** [comment]
It is not interpreted as a heading inside _standard_ code blocks, for which the syntax is to indent the code.

As I wrote, if you want support for _fenced code blocks_ (which is not part of the canonical Markdown specification) then you should install the GitHub Flavoured Markdown bundle, which adds support for this construct.
