### ISSUE TITLE
Support task list items

### ISSUE THREAD

**Issue by ogallagher** [textmate/markdown.tmbundle#54]
> show, don’t tell
>
> -- _somebody_

- [ ] please support task list items
- [ ] with checkboxes instead of bullets
- within a list,
- as [does Github](https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/)
- [x] the end

**Comment by infininight** [comment]
There are dozens of popular Markdown variants but this bundle is focused on the original variant with no modifications. If you want the Github variant you can install that bundle from preferences.
