### ISSUE TITLE
Formatting with multiple fonts and sizes is distracting

### ISSUE THREAD

**Issue by benhourigan** [textmate/markdown.tmbundle#7]
Have been using this bundle with the latest Textmate 2.0 alpha, and find the use of different (variable width) fonts, and at different sizes, distracting.

It ruins the whole typewriter vibe that you get from writing in a text editor--not to mention that there's just something really uncomfortable about combining fixed-width and variable fonts in the same view. It's exposure to this kind of overdesign that writers move to Markdown to escape...

Is it possible to have an option, or a separate bundle in the repository, that sticks to one font and size throughout, like the old bundle that came with Textmate 1.x?

**Comment by louisabraham** [comment]
Hi, I would like to change the font used by the markdown bundle (it is not a fixed width font).

But when I try with View → Font, it only changes the font of the line numbers.

Then, I tried Themes → Settings and deleted all the fontName preferences, but it didn't change anything.

Finally, I created a setting for scope "text.html.markdown" with `{ fontName = 'FreeMono'; }`, but again it didn't work. When I don't put any scope, it changes the font for all bundles but the markdown one…

**Comment by sorbits** [comment]
The body text uses the default font (from View → Font) which defaults 
to the system default’s fixed width font.

If that is not the case for you I suggest you follow the instructions 
here https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

**Comment by louisabraham** [comment]
Thanks, problem solved!
