### ISSUE TITLE
support for "GitHub Flavored Markdown"

### ISSUE THREAD

**Issue by indeyets** [textmate/markdown.tmbundle#9]
Is it possible to add support for [GitHub-specific syntax](http://github.github.com/github-flavored-markdown/)?

I'm especially interested in "Fenced code blocks"

**Comment by MikeMcQuaid** [comment]
TextMate 2 now has a Markdown (GitHub) bundle under "Bundles" that I think may address many of the folks' desires here (repository for the curious: https://github.com/MikeMcQuaid/GitHub-Markdown.tmbundle).
